version: '3.3'
services:
  elasticsearch2:
    container_name: cvat2_elasticsearch
    image: cvat_elasticsearch
    networks:
      - cvat2
    build:
      context: ./components2/analytics/elasticsearch
      args:
        ELK_VERSION: 6.8.23
    volumes:
      - /app/data-cvat/cvat2/cvat_cvat_events:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    restart: always

  kibana2:
    container_name: cvat2_kibana
    image: cvat_kibana
    networks:
      - cvat2
    build:
      context: ./components2/analytics/kibana
      args:
        ELK_VERSION: 6.8.23
    depends_on: ['elasticsearch2']
    restart: always

  cvat2_kibana_setup:
    container_name: cvat2_kibana_setup
    image: openvino/cvat_server
    volumes: ['./components2/analytics/kibana:/home/django/kibana2:ro']
    depends_on: ['cvat2']
    working_dir: '/home/django'
    networks:
      - cvat2
    entrypoint:
      [
        'bash',
        'wait-for-it.sh',
        'elasticsearch2:9200',
        '-t',
        '0',
        '--',
        '/bin/bash',
        'wait-for-it.sh',
        'kibana2:5601',
        '-t',
        '0',
        '--',
        'python3',
        'kibana2/setup.py',
        'kibana2/export.json',
      ]
    environment:
      no_proxy: elasticsearch2,kibana2,${no_proxy}

  logstash2:
    container_name: cvat2_logstash
    image: cvat_logstash
    networks:
      - cvat2
    build:
      context: ./components2/analytics/logstash
      args:
        ELK_VERSION: 6.8.23
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
      LOGSTASH_OUTPUT_HOST: elasticsearch2:9200
      LOGSTASH_OUTPUT_USER:
      LOGSTASH_OUTPUT_PASS:
    depends_on: ['elasticsearch2']
    restart: always

  cvat2:
    environment:
      DJANGO_LOG_SERVER_HOST: logstash2
      DJANGO_LOG_SERVER_PORT: 8080
      CVAT_ANALYTICS: 1

  # traefik:
  #   environment:
  #     CVAT_HOST: cvat2-data.standalone.powerarena.com
  #     DJANGO_LOG_VIEWER_HOST: kibana2
  #     DJANGO_LOG_VIEWER_PORT: 5601
  #   volumes:
  #     - ./components2/analytics/kibana_conf.yml:/etc/traefik/rules/kibana2_conf.yml:ro
